import {Platform, StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import Colors from '../../constants';
export default StyleSheet.create({
  root: {
    flex: 1,
  },
  headerImage: {
    flex: 1,
    resizeMode: 'contain',
    width: wp(100),
    height: hp(100),
  },
  logos: {
    width: wp(8),
    height: wp(8),
    marginBottom: hp(3),
    alignSelf: 'center',
  },
  profile: {
    width: wp(55),
    height: wp(55),
    alignSelf: 'center',
    borderRadius: wp(4),
    marginTop: wp(5),
    borderRadius: wp(30),
  },
  top: {
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'space-between',
    marginTop: Platform.OS == 'ios' ? hp(1.5) : hp(5),
    marginHorizontal: wp(5),
  },
  title: {
    fontSize: 14,
    fontFamily: 'MontserratAlternates-SemiBold',
    letterSpacing: 1,
    color: Colors.white,
    marginLeft: hp(0.7),
  },
  box: {
    flex: 1,
    marginHorizontal: wp(5),
    width: wp(90),
    marginTop: hp(1.5),
  },
  boxinside: {
    backgroundColor: "#1A0B19",
    borderWidth:2,
    borderColor: '#4C0C45',
    borderRadius: wp(4),
    paddingTop: hp(2),
    paddingBottom: hp(2),
    paddingHorizontal: wp(5),
  },
  home: {
    fontSize: 20,
    fontFamily: 'MontserratAlternates-SemiBold',
    letterSpacing: 1,
    fontWeight: 'bold',
    color: Colors.white,
  },
  text: {
    fontSize: 15,
    color: Colors.white,
    textAlign: 'center',
  },
  heart: {
    flexDirection: 'row',
    backgroundColor: 'black',
    alignSelf: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(4),
    paddingVertical: hp(1),
    backgroundColor: '#643BBB',
    borderRadius: wp(10),
    bottom: wp(5),
    marginTop: wp(10),
  },
  name: {
    color: Colors.main_back_color,
    fontSize: 25,
    fontFamily: 'MontserratAlternates-SemiBold',
    letterSpacing: 1,
    textAlign: 'center',
    marginBottom: hp(1),
  },
  detail: {
    color: 'white',
    fontSize: 14,
    alignSelf:'center',
    right:3,
    fontFamily: 'MontserratAlternates-Regular',
    marginBottom:4,
  },
  icn: {
    width: wp(14),
    height: wp(14),
    borderRadius: wp(7),
    backgroundColor: '#312330',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 10,
    
  },
  icns: {
    width: wp(4),
    height: wp(4),
    borderRadius: wp(2),
    backgroundColor: '#EAB951',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 10,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowRadius: 10,
    shadowOpacity: 0.5,
    marginLeft: wp(2),
  },
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
    paddingHorizontal: 16,
  },
  searchContainer: {
    marginTop: 16,
    marginBottom: 20,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ff0eea',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  searchIcon: {
    color: '#666',
    fontSize: 16,
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    color: '#fff',
    fontSize: 16,
    fontWeight: '400',
  },
  closeButton: {
    padding: 4,
  },
  closeIcon: {
    color: '#666',
    fontSize: 18,
    fontWeight: 'bold',
  },
  profileCard: {
    backgroundColor: '#1a1a1a',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ff0eea',
    padding: 20,
  },
  profileHeader: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  avatarContainer: {
    marginRight: 16,
    // backgroundColor:"red",
    width:"100%",
    alignItems:'center'
  },
  avatar: {
    width: 233,
    
    height: 233,
    borderRadius: 150,
  },
  profileInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  nameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent:"center",
    // backgroundColor:'red',
    marginBottom: 4,
  },
  name: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  verifiedBadge: {
    backgroundColor: '#1da1f2',
    left:7,
    top:2,
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkmark: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  username: {
    color: '#666',
    fontSize: 16,
    marginBottom: 8,
  },
  followStats: {
    flexDirection: 'row',
    alignSelf:"center",
    alignItems: 'center',
  },
  followText: {
    color: '#666',
    fontSize: 14,
  },
  followNumber: {
    color: '#fff',
    fontWeight: 'bold',
  },
  separator: {
    color: '#666',
    fontSize: 14,
  },
  bio: {
    color: '#999',
    fontSize: 15,
    textAlign:"center",
    fontFamily: 'MontserratAlternates-Regular',
    lineHeight: 22,
  },
  actionButtons: {
    flexDirection: 'row',
    paddingHorizontal: 20,
  },
  actionButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
  },
  musicButton: {
    backgroundColor: '#ff0eea',
    width: 70,
    height: 70,
    borderRadius: 35,
  },
  xIcon: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '900',
  },
  musicIcon: {
    color: '#fff',
    fontSize: 32,
    fontWeight: '900',
  },
  menuIcon: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '900',
  },
});
