import {Platform, StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import Colors from '../../constants';
export default StyleSheet.create({
  root: {
    flex: 1,
  },
  headerImage: {
    flex: 1,
    resizeMode: 'contain',
    width: wp(100),
    height: hp(100),
  },

  top: {
    marginTop: Platform.OS == 'ios' ? hp(1.5) : hp(5),
    marginBottom: hp(3),
    marginHorizontal: wp(5),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  touchPost: {
    width: wp(25),
    padding: 5,
  },
  title: {
    fontSize: 20,
    fontFamily: 'MontserratAlternates-SemiBold',
    letterSpacing: 1,
    color: Colors.white,
  },

  post: {
    fontSize: 13,
    fontFamily: 'MontserratAlternates-Regular',
    // letterSpacing: 1,
    color: Colors.white,
  },
  box: {
    marginTop: hp(1),
    alignSelf: 'center',
    backgroundColor: '#191919',
    paddingTop: 10,
    elevation: 20,
    borderRadius: 10,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowRadius: 10,
    shadowOpacity: 0.5,
  },
  boxinside: {
    width: wp(90),
    height: hp(75),
    // backgroundColor: Colors.gray,
    borderRadius: wp(4),
    paddingTop: hp(1),
    paddingBottom: hp(3),
    paddingHorizontal: wp(5),
  },

  button: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    width: wp(80),
    height: wp(14),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: hp(4),
  },
  login: {
    fontSize: 16,
    fontFamily: 'MontserratAlternates-SemiBold',
    color: Colors.main_back_color,
    letterSpacing: 1,
  },

  icon: {
    width: wp(12),
    height: wp(12),
  },
  listview: {
    width: wp(80),
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: wp(4),
    // height: hp(20),
    paddingTop: wp(3),
    paddingBottom: wp(3),
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: wp(2),
    // backgroundColor: 'black',
    paddingLeft: wp(5),
    paddingRight: wp(2),
  },
  titleList: {
    fontSize: 16,
    fontFamily: 'MontserratAlternates-SemiBold',
    color: Colors.white,
    letterSpacing: 2,
  },
  listtag: {
    fontSize: 12,
    fontFamily: 'MontserratAlternates-Regular',
    color: 'lightblue',
    marginBottom: hp(0.1),
  },
  listdet: {
    fontSize: 12,
    fontFamily: 'MontserratAlternates-Regular',
    color: 'white',
  },
  listBl: {
    marginTop: wp(1.5),
  },
  btn: {
    backgroundColor: Colors.main_back_color,
    alignSelf: 'flex-end',
    paddingHorizontal: wp(2),
    paddingVertical: wp(0.7),
    borderRadius: wp(1),
    justifyContent: 'center',
  },
  boxmodal: {
    // marginLeft: wp(10),
    // marginRight: wp(13),

    marginBottom: hp(7),
    paddingTop: hp(16),
    alignItems: 'center',
  },
  boxinsidemodal: {
    backgroundColor: Colors.gray,
    borderRadius: wp(4),
    paddingTop: hp(2),
    elevation: 10,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowRadius: 10,
    shadowOpacity: 0.5,
    paddingHorizontal: wp(5),
    marginHorizontal: wp(2),
    paddingBottom: wp(10),
    // height: hp(60),
    width: wp(80),
  },
  input: {
    height: wp(12),
    borderWidth: 1,
    padding: 10,
    borderWidth: 1,
    borderColor: 'grey',
    // backgroundColor: Colors.gray,
    borderRadius: 10,

    paddingLeft: wp(5),
    width: wp(65),
    fontSize: 14,
    color: 'white',
    fontFamily: 'MontserratAlternates-Regular',
  },
  btntext: {
    fontSize: 12,
    fontFamily: 'MontserratAlternates-Regular',
    color: 'white',
  },
  modal: {
    flex: 1,
    // justifyContent: 'center',
    marginTop: hp(20),
    alignItems: 'center',
    alignContent: 'center',
  },
  modalView: {
    backgroundColor: Colors.gray,
    width: wp(80),
    borderRadius: wp(3),
    paddingHorizontal: wp(5),
    paddingTop: wp(2),
  },
  modaljob: {
    flex: 1,
    // justifyContent: 'center',
    marginTop: hp(20),
    alignItems: 'center',
    alignContent: 'center',
  },
  modalViewjob: {
    backgroundColor: Colors.gray,
    width: wp(80),
    height: hp(50),
    borderRadius: wp(3),
    paddingHorizontal: wp(5),
    paddingTop: wp(2),
  },
  modalbtn: {
    backgroundColor: Colors.main_back_color,
    alignSelf: 'flex-end',
    paddingHorizontal: wp(2),
    paddingVertical: wp(1.5),
    borderRadius: wp(1),
    width: wp(40),
    marginTop: wp(10),
    marginBottom: wp(5),
    alignItems: 'center',
    alignSelf: 'center',
  },
  modalbtntext: {
    fontSize: 16,
    fontFamily: 'MontserratAlternates-Regular',
    color: 'white',
  },
  radiotitle: {
    color: Colors.white,
    fontSize: 12,
    fontFamily: 'MontserratAlternates-Regular',
  },
  main: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: Colors.main_back_color,
    paddingBottom: wp(1),
    marginBottom: hp(2),
  },
});
